name: Deploy to Raspberry Pi

on:
    push:
        branches: [master]

    workflow_dispatch:
    
jobs:
    build:
        runs-on: self-hosted
        
        steps:
            - uses: actions/checkout@v2
            
            - name: Install dependencies and compile
              run: |
                npm install
                npm run build
    
    deploy:
        runs-on: self-hosted
        needs: build
        
        steps:
            - name: Run project
              run: |
                npm run serve
